<a href="https://colab.research.google.com/github/luisroldano/Ejercicios_logicos/blob/main/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [62]:
import numpy as np

In [4]:
datos=pd.read_json("https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json")

In [5]:
datos

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [6]:
datos.info

<bound method DataFrame.info of       customerID Churn                                           customer  \
0     0002-ORFBO    No  {'gender': 'Female', 'SeniorCitizen': 0, 'Part...
1     0003-MKNFE    No  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
2     0004-TLHLJ   Yes  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
3     0011-IGKFF   Yes  {'gender': 'Male', 'SeniorCitizen': 1, 'Partne...
4     0013-EXCHZ   Yes  {'gender': 'Female', 'SeniorCitizen': 1, 'Part...
...          ...   ...                                                ...
7262  9987-LUTYD    No  {'gender': 'Female', 'SeniorCitizen': 0, 'Part...
7263  9992-RRAMN   Yes  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
7264  9992-UJOEL    No  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
7265  9993-LHIEB    No  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
7266  9995-HOTOH    No  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...

                                                  phone  \
0        {'PhoneService': 'Yes', 'MultipleLines': 'No'}
1       {'PhoneService': 'Yes', 'MultipleLines': 'Yes'}
2        {'PhoneService': 'Yes', 'MultipleLines': 'No'}
3        {'PhoneService': 'Yes', 'MultipleLines': 'No'}
4        {'PhoneService': 'Yes', 'MultipleLines': 'No'}
...                                                 ...
7262     {'PhoneService': 'Yes', 'MultipleLines': 'No'}
7263    {'PhoneService': 'Yes', 'MultipleLines': 'Yes'}
7264     {'PhoneService': 'Yes', 'MultipleLines': 'No'}
7265     {'PhoneService': 'Yes', 'MultipleLines': 'No'}
7266  {'PhoneService': 'No', 'MultipleLines': 'No ph...

                                               internet  \
0     {'InternetService': 'DSL', 'OnlineSecurity': '...
1     {'InternetService': 'DSL', 'OnlineSecurity': '...
2     {'InternetService': 'Fiber optic', 'OnlineSecu...
3     {'InternetService': 'Fiber optic', 'OnlineSecu...
4     {'InternetService': 'Fiber optic', 'OnlineSecu...
...                                                 ...
7262  {'InternetService': 'DSL', 'OnlineSecurity': '...
7263  {'InternetService': 'Fiber optic', 'OnlineSecu...
7264  {'InternetService': 'DSL', 'OnlineSecurity': '...
7265  {'InternetService': 'DSL', 'OnlineSecurity': '...
7266  {'InternetService': 'DSL', 'OnlineSecurity': '...

                                                account
0     {'Contract': 'One year', 'PaperlessBilling': '...
1     {'Contract': 'Month-to-month', 'PaperlessBilli...
2     {'Contract': 'Month-to-month', 'PaperlessBilli...
3     {'Contract': 'Month-to-month', 'PaperlessBilli...
4     {'Contract': 'Month-to-month', 'PaperlessBilli...
...                                                 ...
7262  {'Contract': 'One year', 'PaperlessBilling': '...
7263  {'Contract': 'Month-to-month', 'PaperlessBilli...
7264  {'Contract': 'Month-to-month', 'PaperlessBilli...
7265  {'Contract': 'Two year', 'PaperlessBilling': '...
7266  {'Contract': 'Two year', 'PaperlessBilling': '...

[7267 rows x 6 columns]>

In [7]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [8]:
datos["customerID"].unique()

array(['0002-ORFBO', '0003-MKNFE', '0004-TLHLJ', ..., '9992-UJOEL',
       '9993-LHIEB', '9995-HOTOH'], dtype=object)

## aplicamos datos.isnull.sum()

In [9]:
datos.isnull().sum()

customerID    0
Churn         0
customer      0
phone         0
internet      0
account       0
dtype: int64

##Con esto demostramos que estas columnas no tienen valores nulos

In [10]:
datos.shape

(7267, 6)

In [11]:
datos['customerID'].unique()

array(['0002-ORFBO', '0003-MKNFE', '0004-TLHLJ', ..., '9992-UJOEL',
       '9993-LHIEB', '9995-HOTOH'], dtype=object)

In [12]:
datos['customerID'].duplicated().sum()

np.int64(0)

##se usa lo de arriba ya que el array de customerid es muy extenso para verificar si ay alguno repetido.

In [13]:
datos['Churn'].unique()

array(['No', 'Yes', ''], dtype=object)

#Primera incoherencia ''

In [14]:
customer_df = datos['customer'].apply(pd.Series)

In [15]:
customer_df

      gender  SeniorCitizen Partner Dependents  tenure
0     Female              0     Yes        Yes       9
1       Male              0      No         No       9
2       Male              0      No         No       4
3       Male              1     Yes         No      13
4     Female              1     Yes         No       3
...      ...            ...     ...        ...     ...
7262  Female              0      No         No      13
7263    Male              0     Yes         No      22
7264    Male              0      No         No       2
7265    Male              0     Yes        Yes      67
7266    Male              0     Yes        Yes      63

[7267 rows x 5 columns]

In [16]:
datos = pd.concat([datos, customer_df], axis=1)

In [17]:
datos.drop(columns=['customer'], inplace=True)

In [18]:
datos

,customerID,Churn,phone,internet,account,gender,SeniorCitizen,Partner,Dependents,tenure
0,0002-ORFBO,No,"{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '...",Female,0,Yes,Yes,9
1,0003-MKNFE,No,"{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,0,No,No,9
2,0004-TLHLJ,Yes,"{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,0,No,No,4
3,0011-IGKFF,Yes,"{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,1,Yes,No,13
4,0013-EXCHZ,Yes,"{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Female,1,Yes,No,3
...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '...",Female,0,No,No,13
7263,9992-RRAMN,Yes,"{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,0,Yes,No,22
7264,9992-UJOEL,No,"{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,0,No,No,2
7265,9993-LHIEB,No,"{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '...",Male,0,Yes,Yes,67
7266,9995-HOTOH,No,"{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '...",Male,0,Yes,Yes,63

In [19]:
datos['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [20]:
datos['SeniorCitizen'].unique()

array([0, 1])

In [21]:
datos['Partner'].unique()

array(['Yes', 'No'], dtype=object)

In [22]:
datos['Dependents'].unique()

array(['Yes', 'No'], dtype=object)

In [23]:
datos['tenure'].unique()

array([ 9,  4, 13,  3, 71, 63,  7, 65, 54, 72,  5, 56, 34,  1, 45, 50, 23,
       55, 26, 69, 11, 37, 49, 66, 67, 20, 43, 59, 12, 27,  2, 25, 29, 14,
       35, 64, 39, 40,  6, 30, 70, 57, 58, 16, 32, 33, 10, 21, 61, 15, 44,
       22, 24, 19, 47, 62, 46, 52,  8, 60, 48, 28, 41, 53, 68, 51, 31, 36,
       17, 18, 38, 42,  0])

In [24]:
internet_df= datos['internet'].apply(pd.Series)

In [25]:
internet_df

,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,DSL,No,Yes,No,Yes,Yes,No
1,DSL,No,No,No,No,No,Yes
2,Fiber optic,No,No,Yes,No,No,No
3,Fiber optic,No,Yes,Yes,No,Yes,Yes
4,Fiber optic,No,No,No,Yes,Yes,No
...,...,...,...,...,...,...,...
7262,DSL,Yes,No,No,Yes,No,No
7263,Fiber optic,No,No,No,No,No,Yes
7264,DSL,No,Yes,No,No,No,No
7265,DSL,Yes,No,Yes,Yes,No,Yes
7266,DSL,Yes,Yes,Yes,No,Yes,Yes

In [26]:
phone_df= datos['phone'].apply(pd.Series)

In [27]:
phone_df

     PhoneService     MultipleLines
0             Yes                No
1             Yes               Yes
2             Yes                No
3             Yes                No
4             Yes                No
...           ...               ...
7262          Yes                No
7263          Yes               Yes
7264          Yes                No
7265          Yes                No
7266           No  No phone service

[7267 rows x 2 columns]

In [28]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7267 non-null   object
 1   Churn          7267 non-null   object
 2   phone          7267 non-null   object
 3   internet       7267 non-null   object
 4   account        7267 non-null   object
 5   gender         7267 non-null   object
 6   SeniorCitizen  7267 non-null   int64
 7   Partner        7267 non-null   object
 8   Dependents     7267 non-null   object
 9   tenure         7267 non-null   int64
dtypes: int64(2), object(8)
memory usage: 567.9+ KB

In [29]:
datos.columns

Index(['customerID', 'Churn', 'phone', 'internet', 'account', 'gender',
       'SeniorCitizen', 'Partner', 'Dependents', 'tenure'],
      dtype='object')

In [30]:
datos = pd.concat([datos, internet_df], axis=1)
datos.drop(columns=['internet'], inplace=True)

In [31]:
datos = pd.concat([datos, phone_df], axis=1)
datos.drop(columns=['phone'], inplace=True)

In [32]:
datos

,customerID,Churn,account,gender,SeniorCitizen,Partner,Dependents,tenure,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PhoneService,MultipleLines
0,0002-ORFBO,No,"{'Contract': 'One year', 'PaperlessBilling': '...",Female,0,Yes,Yes,9,DSL,No,Yes,No,Yes,Yes,No,Yes,No
1,0003-MKNFE,No,"{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,0,No,No,9,DSL,No,No,No,No,No,Yes,Yes,Yes
2,0004-TLHLJ,Yes,"{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,0,No,No,4,Fiber optic,No,No,Yes,No,No,No,Yes,No
3,0011-IGKFF,Yes,"{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,1,Yes,No,13,Fiber optic,No,Yes,Yes,No,Yes,Yes,Yes,No
4,0013-EXCHZ,Yes,"{'Contract': 'Month-to-month', 'PaperlessBilli...",Female,1,Yes,No,3,Fiber optic,No,No,No,Yes,Yes,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'Contract': 'One year', 'PaperlessBilling': '...",Female,0,No,No,13,DSL,Yes,No,No,Yes,No,No,Yes,No
7263,9992-RRAMN,Yes,"{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,0,Yes,No,22,Fiber optic,No,No,No,No,No,Yes,Yes,Yes
7264,9992-UJOEL,No,"{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,0,No,No,2,DSL,No,Yes,No,No,No,No,Yes,No
7265,9993-LHIEB,No,"{'Contract': 'Two year', 'PaperlessBilling': '...",Male,0,Yes,Yes,67,DSL,Yes,No,Yes,Yes,No,Yes,Yes,No
7266,9995-HOTOH,No,"{'Contract': 'Two year', 'PaperlessBilling': '...",Male,0,Yes,Yes,63,DSL,Yes,Yes,Yes,No,Yes,Yes,No,No phone service

In [33]:
account_pd=datos["account"].apply(pd.Series)

In [34]:
account_pd

,Contract,PaperlessBilling,PaymentMethod,Charges
0,One year,Yes,Mailed check,"{'Monthly': 65.6, 'Total': '593.3'}"
1,Month-to-month,No,Mailed check,"{'Monthly': 59.9, 'Total': '542.4'}"
2,Month-to-month,Yes,Electronic check,"{'Monthly': 73.9, 'Total': '280.85'}"
3,Month-to-month,Yes,Electronic check,"{'Monthly': 98.0, 'Total': '1237.85'}"
4,Month-to-month,Yes,Mailed check,"{'Monthly': 83.9, 'Total': '267.4'}"
...,...,...,...,...
7262,One year,No,Mailed check,"{'Monthly': 55.15, 'Total': '742.9'}"
7263,Month-to-month,Yes,Electronic check,"{'Monthly': 85.1, 'Total': '1873.7'}"
7264,Month-to-month,Yes,Mailed check,"{'Monthly': 50.3, 'Total': '92.75'}"
7265,Two year,No,Mailed check,"{'Monthly': 67.85, 'Total': '4627.65'}"
7266,Two year,No,Electronic check,"{'Monthly': 59.0, 'Total': '3707.6'}"

In [35]:
charges_pd= account_pd["Charges"].apply(pd.Series)

In [36]:
charges_pd

      Monthly    Total
0       65.60    593.3
1       59.90    542.4
2       73.90   280.85
3       98.00  1237.85
4       83.90    267.4
...       ...      ...
7262    55.15    742.9
7263    85.10   1873.7
7264    50.30    92.75
7265    67.85  4627.65
7266    59.00   3707.6

[7267 rows x 2 columns]

In [41]:

datos.drop(columns=['Charges'], inplace=True)

In [42]:
datos

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,InternetService,OnlineSecurity,OnlineBackup,...,PaperlessBilling,PaymentMethod,Monthly,Total,Contract,PaperlessBilling,PaymentMethod,Contract,PaperlessBilling,PaymentMethod
0,0002-ORFBO,No,Female,0,Yes,Yes,9,DSL,No,Yes,...,Yes,Mailed check,65.60,593.3,One year,Yes,Mailed check,One year,Yes,Mailed check
1,0003-MKNFE,No,Male,0,No,No,9,DSL,No,No,...,No,Mailed check,59.90,542.4,Month-to-month,No,Mailed check,Month-to-month,No,Mailed check
2,0004-TLHLJ,Yes,Male,0,No,No,4,Fiber optic,No,No,...,Yes,Electronic check,73.90,280.85,Month-to-month,Yes,Electronic check,Month-to-month,Yes,Electronic check
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Fiber optic,No,Yes,...,Yes,Electronic check,98.00,1237.85,Month-to-month,Yes,Electronic check,Month-to-month,Yes,Electronic check
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Fiber optic,No,No,...,Yes,Mailed check,83.90,267.4,Month-to-month,Yes,Mailed check,Month-to-month,Yes,Mailed check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,DSL,Yes,No,...,No,Mailed check,55.15,742.9,One year,No,Mailed check,One year,No,Mailed check
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Fiber optic,No,No,...,Yes,Electronic check,85.10,1873.7,Month-to-month,Yes,Electronic check,Month-to-month,Yes,Electronic check
7264,9992-UJOEL,No,Male,0,No,No,2,DSL,No,Yes,...,Yes,Mailed check,50.30,92.75,Month-to-month,Yes,Mailed check,Month-to-month,Yes,Mailed check
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,DSL,Yes,No,...,No,Mailed check,67.85,4627.65,Two year,No,Mailed check,Two year,No,Mailed check
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,DSL,Yes,Yes,...,No,Electronic check,59.00,3707.6,Two year,No,Electronic check,Two year,No,Electronic check

In [44]:
duplicadas = datos.T.duplicated()
datos.columns[duplicadas]

Index(['Contract', 'PaperlessBilling', 'PaymentMethod', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [45]:
datos

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,InternetService,OnlineSecurity,OnlineBackup,...,PaperlessBilling,PaymentMethod,Monthly,Total,Contract,PaperlessBilling,PaymentMethod,Contract,PaperlessBilling,PaymentMethod
0,0002-ORFBO,No,Female,0,Yes,Yes,9,DSL,No,Yes,...,Yes,Mailed check,65.60,593.3,One year,Yes,Mailed check,One year,Yes,Mailed check
1,0003-MKNFE,No,Male,0,No,No,9,DSL,No,No,...,No,Mailed check,59.90,542.4,Month-to-month,No,Mailed check,Month-to-month,No,Mailed check
2,0004-TLHLJ,Yes,Male,0,No,No,4,Fiber optic,No,No,...,Yes,Electronic check,73.90,280.85,Month-to-month,Yes,Electronic check,Month-to-month,Yes,Electronic check
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Fiber optic,No,Yes,...,Yes,Electronic check,98.00,1237.85,Month-to-month,Yes,Electronic check,Month-to-month,Yes,Electronic check
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Fiber optic,No,No,...,Yes,Mailed check,83.90,267.4,Month-to-month,Yes,Mailed check,Month-to-month,Yes,Mailed check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,DSL,Yes,No,...,No,Mailed check,55.15,742.9,One year,No,Mailed check,One year,No,Mailed check
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Fiber optic,No,No,...,Yes,Electronic check,85.10,1873.7,Month-to-month,Yes,Electronic check,Month-to-month,Yes,Electronic check
7264,9992-UJOEL,No,Male,0,No,No,2,DSL,No,Yes,...,Yes,Mailed check,50.30,92.75,Month-to-month,Yes,Mailed check,Month-to-month,Yes,Mailed check
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,DSL,Yes,No,...,No,Mailed check,67.85,4627.65,Two year,No,Mailed check,Two year,No,Mailed check
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,DSL,Yes,Yes,...,No,Electronic check,59.00,3707.6,Two year,No,Electronic check,Two year,No,Electronic check

In [46]:
datos = datos.loc[:, ~datos.columns.duplicated()]

In [47]:
datos

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,PhoneService,MultipleLines,Contract,PaperlessBilling,PaymentMethod,Monthly,Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,DSL,No,Yes,...,Yes,Yes,No,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,DSL,No,No,...,No,No,Yes,Yes,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Fiber optic,No,No,...,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Fiber optic,No,Yes,...,No,Yes,Yes,Yes,No,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Fiber optic,No,No,...,Yes,Yes,No,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,DSL,Yes,No,...,Yes,No,No,Yes,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Fiber optic,No,No,...,No,No,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,DSL,No,Yes,...,No,No,No,Yes,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,DSL,Yes,No,...,Yes,No,Yes,Yes,No,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,DSL,Yes,Yes,...,No,Yes,Yes,No,No phone service,Two year,No,Electronic check,59.00,3707.6

In [48]:
list(datos.columns)

['customerID',
 'Churn',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'PhoneService',
 'MultipleLines',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'Monthly',
 'Total']

In [50]:
datos['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [51]:
datos['OnlineSecurity'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

#columna gasto diario

In [54]:
datos.drop(columns=['Cuentas_Diarias'],inplace=True)

/tmp/ipykernel_540/318314414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos.drop(columns=['Cuentas_Diarias'],inplace=True)

In [56]:
datos["Cuentas_Diarias"] = (datos["Monthly"] / 30).round(3)

/tmp/ipykernel_540/1326363999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos["Cuentas_Diarias"] = (datos["Monthly"] / 30).round(3)

In [57]:
datos

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,PhoneService,MultipleLines,Contract,PaperlessBilling,PaymentMethod,Monthly,Total,Cuentas_Diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,DSL,No,Yes,...,Yes,No,Yes,No,One year,Yes,Mailed check,65.60,593.3,2.187
1,0003-MKNFE,No,Male,0,No,No,9,DSL,No,No,...,No,Yes,Yes,Yes,Month-to-month,No,Mailed check,59.90,542.4,1.997
2,0004-TLHLJ,Yes,Male,0,No,No,4,Fiber optic,No,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Fiber optic,No,Yes,...,Yes,Yes,Yes,No,Month-to-month,Yes,Electronic check,98.00,1237.85,3.267
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Fiber optic,No,No,...,Yes,No,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4,2.797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,DSL,Yes,No,...,No,No,Yes,No,One year,No,Mailed check,55.15,742.9,1.838
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Fiber optic,No,No,...,No,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7,2.837
7264,9992-UJOEL,No,Male,0,No,No,2,DSL,No,Yes,...,No,No,Yes,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.677
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,DSL,Yes,No,...,No,Yes,Yes,No,Two year,No,Mailed check,67.85,4627.65,2.262
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,DSL,Yes,Yes,...,Yes,Yes,No,No phone service,Two year,No,Electronic check,59.00,3707.6,1.967

#Análisis Descriptivo

In [58]:
datos.describe()

       SeniorCitizen       tenure      Monthly  Cuentas_Diarias
count    7267.000000  7267.000000  7267.000000      7267.000000
mean        0.162653    32.346498    64.720098         2.157341
std         0.369074    24.571773    30.129572         1.004322
min         0.000000     0.000000    18.250000         0.608000
25%         0.000000     9.000000    35.425000         1.181000
50%         0.000000    29.000000    70.300000         2.343000
75%         0.000000    55.000000    89.875000         2.996000
max         1.000000    72.000000   118.750000         3.958000

#En este paso, el objetivo es comprender cómo está distribuida la variable "churn" (evasión) entre los clientes. Utiliza gráficos para visualizar la proporción de clientes que permanecieron y los que se dieron de baja.

In [59]:
datos["Churn"].value_counts()

Churn
No     5174
Yes    1869
        224
Name: count, dtype: int64

In [60]:
datos["Churn"].value_counts(normalize=True) * 100

Churn
No     71.198569
Yes    25.719004
        3.082427
Name: proportion, dtype: float64

In [61]:
datos['Churn'].unique()

array(['No', 'Yes', ''], dtype=object)

In [63]:
datos["Churn"] = datos["Churn"].replace("", np.nan)
datos = datos.dropna(subset=["Churn"])

/tmp/ipykernel_540/494960788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos["Churn"] = datos["Churn"].replace("", np.nan)

In [64]:
datos['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [65]:
datos["Churn"].value_counts(normalize=True) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

#aqui se observa que el 73% de las personas continuan con el servicio mientras que el 26% de las personas se dieron de baja de los ervicios

####

#Recuento de evasión por variables categóricas

In [67]:
datos.groupby("gender")["Churn"].value_counts(normalize=True).unstack() * 100

Churn          No        Yes
gender
Female  73.079128  26.920872
Male    73.839662  26.160338

In [68]:
datos.groupby("Contract")["Churn"].value_counts(normalize=True).unstack() * 100

Churn                  No        Yes
Contract
Month-to-month  57.290323  42.709677
One year        88.730482  11.269518
Two year        97.168142   2.831858

In [69]:
datos.groupby("PaymentMethod")["Churn"].value_counts(normalize=True).unstack() * 100

Churn                             No        Yes
PaymentMethod
Bank transfer (automatic)  83.290155  16.709845
Credit card (automatic)    84.756899  15.243101
Electronic check           54.714588  45.285412
Mailed check               80.893300  19.106700

#Conteo de evasión por variables numéricas

In [ ]:
datos.groupby("Churn")[["tenure", "Monthly", "Total", "Cuentas_Diarias"]].describe()

In [72]:
cols_numericas = ["tenure", "Monthly", "Total", "Cuentas_Diarias"]

for col in cols_numericas:
    datos[col] = pd.to_numeric(datos[col], errors="coerce")

/tmp/ipykernel_540/2551137249.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos[col] = pd.to_numeric(datos[col], errors="coerce")

In [74]:
datos = datos.dropna(subset=cols_numericas)

In [76]:
datos.groupby("Churn")[cols_numericas].mean()

          tenure    Monthly        Total  Cuentas_Diarias
Churn
No     37.650010  61.307408  2555.344141         2.043585
Yes    17.979133  74.441332  1531.796094         2.481381